services:
    nginx:
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - "8000:80"
        networks:
            - internal
        volumes:
            - ./:/var/www/html/

    php:
        restart: unless-stopped
        image: php:8.4-fpm-alpine
        networks:
            - internal
        volumes:
            - ./:/var/www/html/

networks:
    internal:
        driver: bridge
